Add AffineLoopInterchange pass
HarshVardhanKumar/llvm-project pull request #1
Opened 2020-08-01 17:25 UTC by HarshVardhanKumar

Adds a loop interchange pass to the Affine dialect.
The pass works only for loopnests having rectangular iteration space and no Affine-If statements.
In all other cases, it detects the absence of the above conditions and simply bails out leaving that particular loopnest unchanged.
The pass works for both - imperfectly nested loop nests as well as perfectly nested ones.

2020-08-01 17:40 UTC, bondhugula requested changes
Please see this initial set of comments - the same fixes need to be made throughout.

2020-08-01 17:40 UTC, bondhugula commented on mlir/include/mlir/Dialect/Affine/Passes.td
> +  let summary = "Performs loop interchange of all affine loopnests";
loopnests -> loop nests

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +//===- affineLoopInterchange.cpp - Code to perform loop interchange-----===//
a -> A
Code -> Pass

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +//
Empty lines.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +#include <unordered_map>
Prune this list to remove unnecessary header list.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +
Avoid #define's. Instead use const / constexpr variables inside your LoopInterchange struct.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +/// <returns>Returns True if an "Affine-if" statement found.</returns>
Just /// comments is enough. The tags aren't needed - please see other code for reference. Include parameter names in backticks.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +  return iffound;
Use `WalkResult::interrupt()` and `wasInterrupted()` - you won't need the flag. In any case, flags should be `bool` and not `int`.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +bool isRectangularAffineForLoopNest(
`static` method please. You won't need llvm:: on SmallVector.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +    auto *srcOpInst = loadAndStoreOpInsts[i];
Drop `inst` suffixes here. `srcOp`. Also avoid using `auto` unless it's obvious and improves readability - it hampers readability here. Spell out the type. Similarly at other places.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +    // all for a single instruction
All comments have to be proper and grammatically correct sentences. Terminate with a full stop. Fix everywhere else.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +          }
?

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +bool checkColumnIsZero(llvm::SmallVector<std::vector<int64_t>, 0> &accessMatrix,
accessMatrix is read-only. Pass as ArrayRef.

2020-08-01 17:40 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/AffineLoopInterchange.cpp
> +                0) { // both upper and lower bound have same signs
No trailing comment.

2020-08-01 17:41 UTC, bondhugula requested changes
Please add test cases without which this would be incomplete.

2020-08-04 17:12 UTC, closed without merging

2020-08-04 17:13 UTC, HarshVardhanKumar commented
Will do the modifications.

2020-08-04 17:27 UTC, bondhugula commented
Please don't close and create a new PR. Instead, just update and force push.